plugins{
    id 'maven-publish'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}
apply plugin: 'java'
apply plugin: 'com.github.johnrengelman.shadow'


group = 'org.nyxcode.wurm'

version = '3.2'

description = "A mod that acts as a discord relay between Wurm kingdom chat and a discord server"

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}


repositories {
    mavenCentral()
    maven { url "https://gotti.no-ip.org/maven/repository" }
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'net.dv8tion:JDA:6.2.0'
    compileOnly 'org.gotti.wurmunlimited:server-modlauncher:0.40'
    compileOnly 'com.github.Sindusk:sindusklibrary:v2.1'
}

jar {
    archiveFileName = "${project.name}.jar"
}

shadowJar {
    dependencies {
        exclude(dependency('org.gotti.wurmunlimited:server-modlauncher:0.40'))
        exclude(dependency('org.gotti.wurmunlimited:common:3127452'))
        exclude(dependency('org.gotti.wurmunlimited:server:3127452'))
    }
    archiveFileName = "${project.name}.jar"
}

task dist(type: Zip) {
    into("mods", {
        into(project.name, {
            from shadowJar
        })

        from fileTree(dir: 'mods', include: '*')
    })

    archiveFileName = "${project.name}-${project.version}.zip"
}
